# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/christian/Documents/LGA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/christian/Documents/LGA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/christian/Documents/LGA/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christian/Documents/LGA/CMakeFiles /home/christian/Documents/LGA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christian/Documents/LGA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named WRECK

# Build rule for target.
WRECK: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WRECK
.PHONY : WRECK

# fast build rule for target.
WRECK/fast:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/build
.PHONY : WRECK/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

cfg.o: cfg.cpp.o

.PHONY : cfg.o

# target to build an object file
cfg.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/cfg.cpp.o
.PHONY : cfg.cpp.o

cfg.i: cfg.cpp.i

.PHONY : cfg.i

# target to preprocess a source file
cfg.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/cfg.cpp.i
.PHONY : cfg.cpp.i

cfg.s: cfg.cpp.s

.PHONY : cfg.s

# target to generate assembly for a file
cfg.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/cfg.cpp.s
.PHONY : cfg.cpp.s

derivesToLambda.o: derivesToLambda.cpp.o

.PHONY : derivesToLambda.o

# target to build an object file
derivesToLambda.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/derivesToLambda.cpp.o
.PHONY : derivesToLambda.cpp.o

derivesToLambda.i: derivesToLambda.cpp.i

.PHONY : derivesToLambda.i

# target to preprocess a source file
derivesToLambda.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/derivesToLambda.cpp.i
.PHONY : derivesToLambda.cpp.i

derivesToLambda.s: derivesToLambda.cpp.s

.PHONY : derivesToLambda.s

# target to generate assembly for a file
derivesToLambda.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/derivesToLambda.cpp.s
.PHONY : derivesToLambda.cpp.s

first.o: first.cpp.o

.PHONY : first.o

# target to build an object file
first.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/first.cpp.o
.PHONY : first.cpp.o

first.i: first.cpp.i

.PHONY : first.i

# target to preprocess a source file
first.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/first.cpp.i
.PHONY : first.cpp.i

first.s: first.cpp.s

.PHONY : first.s

# target to generate assembly for a file
first.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/first.cpp.s
.PHONY : first.cpp.s

follow.o: follow.cpp.o

.PHONY : follow.o

# target to build an object file
follow.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/follow.cpp.o
.PHONY : follow.cpp.o

follow.i: follow.cpp.i

.PHONY : follow.i

# target to preprocess a source file
follow.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/follow.cpp.i
.PHONY : follow.cpp.i

follow.s: follow.cpp.s

.PHONY : follow.s

# target to generate assembly for a file
follow.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/follow.cpp.s
.PHONY : follow.cpp.s

item.o: item.cpp.o

.PHONY : item.o

# target to build an object file
item.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/item.cpp.o
.PHONY : item.cpp.o

item.i: item.cpp.i

.PHONY : item.i

# target to preprocess a source file
item.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/item.cpp.i
.PHONY : item.cpp.i

item.s: item.cpp.s

.PHONY : item.s

# target to generate assembly for a file
item.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/item.cpp.s
.PHONY : item.cpp.s

ll-table.o: ll-table.cpp.o

.PHONY : ll-table.o

# target to build an object file
ll-table.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/ll-table.cpp.o
.PHONY : ll-table.cpp.o

ll-table.i: ll-table.cpp.i

.PHONY : ll-table.i

# target to preprocess a source file
ll-table.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/ll-table.cpp.i
.PHONY : ll-table.cpp.i

ll-table.s: ll-table.cpp.s

.PHONY : ll-table.s

# target to generate assembly for a file
ll-table.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/ll-table.cpp.s
.PHONY : ll-table.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/main.cpp.s
.PHONY : main.cpp.s

parser.o: parser.cpp.o

.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i

.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s

.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/parser.cpp.s
.PHONY : parser.cpp.s

predict.o: predict.cpp.o

.PHONY : predict.o

# target to build an object file
predict.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/predict.cpp.o
.PHONY : predict.cpp.o

predict.i: predict.cpp.i

.PHONY : predict.i

# target to preprocess a source file
predict.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/predict.cpp.i
.PHONY : predict.cpp.i

predict.s: predict.cpp.s

.PHONY : predict.s

# target to generate assembly for a file
predict.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/predict.cpp.s
.PHONY : predict.cpp.s

regex.o: regex.cpp.o

.PHONY : regex.o

# target to build an object file
regex.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/regex.cpp.o
.PHONY : regex.cpp.o

regex.i: regex.cpp.i

.PHONY : regex.i

# target to preprocess a source file
regex.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/regex.cpp.i
.PHONY : regex.cpp.i

regex.s: regex.cpp.s

.PHONY : regex.s

# target to generate assembly for a file
regex.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/regex.cpp.s
.PHONY : regex.cpp.s

setUnion.o: setUnion.cpp.o

.PHONY : setUnion.o

# target to build an object file
setUnion.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/setUnion.cpp.o
.PHONY : setUnion.cpp.o

setUnion.i: setUnion.cpp.i

.PHONY : setUnion.i

# target to preprocess a source file
setUnion.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/setUnion.cpp.i
.PHONY : setUnion.cpp.i

setUnion.s: setUnion.cpp.s

.PHONY : setUnion.s

# target to generate assembly for a file
setUnion.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/setUnion.cpp.s
.PHONY : setUnion.cpp.s

token.o: token.cpp.o

.PHONY : token.o

# target to build an object file
token.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/token.cpp.o
.PHONY : token.cpp.o

token.i: token.cpp.i

.PHONY : token.i

# target to preprocess a source file
token.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/token.cpp.i
.PHONY : token.cpp.i

token.s: token.cpp.s

.PHONY : token.s

# target to generate assembly for a file
token.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/token.cpp.s
.PHONY : token.cpp.s

util.o: util.cpp.o

.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i

.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s

.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/WRECK.dir/build.make CMakeFiles/WRECK.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... NightlyMemCheck"
	@echo "... NightlyTest"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyMemoryCheck"
	@echo "... ExperimentalTest"
	@echo "... ContinuousUpdate"
	@echo "... NightlyUpdate"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... Experimental"
	@echo "... ContinuousCoverage"
	@echo "... ExperimentalConfigure"
	@echo "... Continuous"
	@echo "... Nightly"
	@echo "... NightlySubmit"
	@echo "... NightlyStart"
	@echo "... ExperimentalCoverage"
	@echo "... WRECK"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalStart"
	@echo "... package"
	@echo "... NightlyBuild"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousStart"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousTest"
	@echo "... ContinuousSubmit"
	@echo "... cfg.o"
	@echo "... cfg.i"
	@echo "... cfg.s"
	@echo "... derivesToLambda.o"
	@echo "... derivesToLambda.i"
	@echo "... derivesToLambda.s"
	@echo "... first.o"
	@echo "... first.i"
	@echo "... first.s"
	@echo "... follow.o"
	@echo "... follow.i"
	@echo "... follow.s"
	@echo "... item.o"
	@echo "... item.i"
	@echo "... item.s"
	@echo "... ll-table.o"
	@echo "... ll-table.i"
	@echo "... ll-table.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... predict.o"
	@echo "... predict.i"
	@echo "... predict.s"
	@echo "... regex.o"
	@echo "... regex.i"
	@echo "... regex.s"
	@echo "... setUnion.o"
	@echo "... setUnion.i"
	@echo "... setUnion.s"
	@echo "... token.o"
	@echo "... token.i"
	@echo "... token.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

